Call abp generate-crud HRIS\Department auth
Call abp generate-crud HRIS\Division auth
Call abp generate-crud HRIS\Employee auth
Call abp generate-crud HRIS\EmployeeAttachment auth
Call abp generate-crud HRIS\EmployeeCertificate auth
Call abp generate-crud HRIS\EmployeeOffenseAndViolation auth
Call abp generate-crud HRIS\EmployeePayrollState auth
Call abp generate-crud HRIS\EmployeeScheduleState auth
Call abp generate-crud HRIS\EmployeeState auth
Call abp generate-crud HRIS\EmployeeWorkHistory auth
Call abp generate-crud HRIS\EmploymentType auth
Call abp generate-crud HRIS\Group auth
Call abp generate-crud HRIS\Industry auth
Call abp generate-crud HRIS\Municipality auth
Call abp generate-crud HRIS\Nationality auth
Call abp generate-crud HRIS\PayGroup auth
Call abp generate-crud HRIS\Position auth
Call abp generate-crud HRIS\Province auth
Call abp generate-crud HRIS\Rank auth
Call abp generate-crud HRIS\Region auth
Call abp generate-crud HRIS\Religion auth
Call abp generate-crud HRIS\Section auth
Call abp generate-crud HRIS\Site auth